### ISSUE TITLE
Deploy 0.0.1 release (Phase 0)

### ISSUE THREAD

**Issue by msashkin** [odessajavaclub/coffee-pot#40]
- Add a GitHub action, which triggers on tag pushing (v*). Alternative is to create draft releases using gh actions
- It should create a Jar artifact which is uploaded to GitHub registry
- Also, it should create a Docker image with a specific tag which is pushed to GitHub registry

**Comment by apletnev** [comment]
We should avoid creating a release by maven plugin because it is redundant dependency and we should separate that process.
We have to do that by Github Actions. I've modified a build flow, please, see my PR: https://github.com/odessajavaclub/coffee-pot/pull/46

**Comment by msashkin** [comment]
@apletnev I've updated description with a hypothetical scenario
